"""Adds attributes to classes in Models.py

Revision ID: e471bb6f8e8c
Revises: 452c185f2ec6
Create Date: 2024-04-21 23:27:21.402866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e471bb6f8e8c'
down_revision = '452c185f2ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_card_thumbnail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('blog_card_banner', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('blog_card_banner')
        batch_op.drop_column('blog_card_thumbnail')

    # ### end Alembic commands ###
